// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIHLI8wa-DAsci6fGVnPIwLB1W4pG4mY',
    appId: '1:1001660030744:web:2b39f90aa411c6d0fc486d',
    messagingSenderId: '1001660030744',
    projectId: 'fitlife-app-bd9b4',
    authDomain: 'fitlife-app-bd9b4.firebaseapp.com',
    storageBucket: 'fitlife-app-bd9b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf8Snq2D6Ln9i_kSimkjtwBrDuPAqJzDs',
    appId: '1:1001660030744:android:5730f8428bdedabcfc486d',
    messagingSenderId: '1001660030744',
    projectId: 'fitlife-app-bd9b4',
    storageBucket: 'fitlife-app-bd9b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBomoOhE03b6c9qbwYKMJVc9NHUw7XEBwo',
    appId: '1:1001660030744:ios:554a6f33c5371e76fc486d',
    messagingSenderId: '1001660030744',
    projectId: 'fitlife-app-bd9b4',
    storageBucket: 'fitlife-app-bd9b4.firebasestorage.app',
    iosBundleId: 'com.example.fitlifeApp',
  );
}
