// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATekogZr4ONXOpYn912sc5_QCEVLk10BU',
    appId: '1:984332560461:web:9b4f49a7427c9531c01404',
    messagingSenderId: '984332560461',
    projectId: 'fitlife-a042d',
    authDomain: 'fitlife-a042d.firebaseapp.com',
    storageBucket: 'fitlife-a042d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNhPs9MnqFr_Ll-Uqg27_Hts01DvpOMPM',
    appId: '1:984332560461:android:7ce19e19d396bff4c01404',
    messagingSenderId: '984332560461',
    projectId: 'fitlife-a042d',
    storageBucket: 'fitlife-a042d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMcr9jL7WD9MgCjuxYdhLuvFwFQ7NTtxI',
    appId: '1:984332560461:ios:bf6c3b645eec08b6c01404',
    messagingSenderId: '984332560461',
    projectId: 'fitlife-a042d',
    storageBucket: 'fitlife-a042d.firebasestorage.app',
    iosBundleId: 'com.example.fitlifeApp',
  );
}
